---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  label_master_loop.sh: |
    #!/bin/bash
    if [[ $1 == "--config" ]] ; then
      cat <<EOF
    {
      "configVersion":"v1",
      "kubernetes": [
        {
          "apiVersion": "v1",
          "kind": "Endpoints",
          "executeHookOnEvent": [
            "Added",
            "Modified"
          ],
          "labelSelector": {
            "matchLabels": {
            {{- range $i, $val := .Values.label_endpoint }}
              {{ $i | quote }}: {{ $val | quote }}
            {{- end }}
            }
          },
          "namespace": {
            "nameSelector": {
              "matchNames": [
                {{ .Release.Namespace | quote }}
              ]
            }
          }
        }
      ]
    }
    EOF
    else

      function atoi
      {
        #Returns the integer representation of an IP arg, passed in ascii dotted-decimal notation (x.x.x.x)
        IP=$1; IPNUM=0
        for (( i=0 ; i<4 ; ++i )); do
          ((IPNUM+=${IP%%.*}*$((256**$((3-${i}))))))
          IP=${IP#*.}
        done
        echo $IPNUM
      }

      ns={{ .Release.Namespace }}
      maxIp="0"

      # find all IP from endpoint
      for ip in $(jq -r '.[].objects[].object.subsets[].addresses[].ip' $BINDING_CONTEXT_PATH)
      do
        a=$(atoi $ip)
        b=$(atoi $maxIp)

        # compare IPs, remember max IP
        if [[ $a > $b ]]; then
          maxIp=$ip
        fi
      done

      # get podName by IP
      podName=$(jq -r '.[].objects[].object.subsets[].addresses[]|select(.ip == "'$maxIp'")|.targetRef.name' $BINDING_CONTEXT_PATH)

      echo "Found pod with max ip: $podName, $maxIp"

      for pod in $(kubectl -n $ns get po -l loop-master -o json | jq -r '.items[] | .metadata.name')
      do
        if [ "$pod" != "$podName" ]; then
          echo "Unlabel $pod for master"
          kubectl -n $ns label pod $podName loop-master-
        fi
      done

      echo "Label $podName for master"
      kubectl -n $ns label pod $podName --overwrite loop-master=""

    fi
